Fix/import brace-expansion errors (#642)
* On Docker runs fail due to file:///app/oobee/node_modules/glob/node_modules/minimatch/dist/esm/index.js:1
import { expand } from 'brace-expansion';
SyntaxError: The requested module 'brace-expansion' does not provide an export named 'expand'

* Temp workaround by using npm install for Dockerfile